/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 26
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 21
#define ALIAS_COUNT 1
#define TOKEN_COUNT 12
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 9
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 6
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_header_token1 = 1,
  anon_sym_COLON = 2,
  aux_sym_header_token2 = 3,
  aux_sym_field_token1 = 4,
  anon_sym_LBRACKtypst_RBRACK = 5,
  anon_sym_LBRACK_SLASHtypst_RBRACK = 6,
  anon_sym_LBRACKlatex_RBRACK = 7,
  anon_sym_LBRACK_SLASHlatex_RBRACK = 8,
  aux_sym__block_content_token1 = 9,
  aux_sym__block_content_token2 = 10,
  sym_text = 11,
  sym_source_file = 12,
  sym_header = 13,
  sym_field = 14,
  sym_typst_block = 15,
  sym_latex_block = 16,
  sym__block_content = 17,
  aux_sym_source_file_repeat1 = 18,
  aux_sym_field_repeat1 = 19,
  aux_sym__block_content_repeat1 = 20,
  alias_sym_latex = 21,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_header_token1] = "key_name",
  [anon_sym_COLON] = ":",
  [aux_sym_header_token2] = "value_content",
  [aux_sym_field_token1] = "field_name",
  [anon_sym_LBRACKtypst_RBRACK] = "typst_open_tag",
  [anon_sym_LBRACK_SLASHtypst_RBRACK] = "typst_close_tag",
  [anon_sym_LBRACKlatex_RBRACK] = "latex_open_tag",
  [anon_sym_LBRACK_SLASHlatex_RBRACK] = "latex_close_tag",
  [aux_sym__block_content_token1] = "_block_content_token1",
  [aux_sym__block_content_token2] = "_block_content_token2",
  [sym_text] = "text",
  [sym_source_file] = "source_file",
  [sym_header] = "header",
  [sym_field] = "field",
  [sym_typst_block] = "typst_block",
  [sym_latex_block] = "latex_block",
  [sym__block_content] = "typst",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_field_repeat1] = "field_repeat1",
  [aux_sym__block_content_repeat1] = "_block_content_repeat1",
  [alias_sym_latex] = "latex",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_header_token1] = aux_sym_header_token1,
  [anon_sym_COLON] = anon_sym_COLON,
  [aux_sym_header_token2] = aux_sym_header_token2,
  [aux_sym_field_token1] = aux_sym_field_token1,
  [anon_sym_LBRACKtypst_RBRACK] = anon_sym_LBRACKtypst_RBRACK,
  [anon_sym_LBRACK_SLASHtypst_RBRACK] = anon_sym_LBRACK_SLASHtypst_RBRACK,
  [anon_sym_LBRACKlatex_RBRACK] = anon_sym_LBRACKlatex_RBRACK,
  [anon_sym_LBRACK_SLASHlatex_RBRACK] = anon_sym_LBRACK_SLASHlatex_RBRACK,
  [aux_sym__block_content_token1] = aux_sym__block_content_token1,
  [aux_sym__block_content_token2] = aux_sym__block_content_token2,
  [sym_text] = sym_text,
  [sym_source_file] = sym_source_file,
  [sym_header] = sym_header,
  [sym_field] = sym_field,
  [sym_typst_block] = sym_typst_block,
  [sym_latex_block] = sym_latex_block,
  [sym__block_content] = sym__block_content,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_field_repeat1] = aux_sym_field_repeat1,
  [aux_sym__block_content_repeat1] = aux_sym__block_content_repeat1,
  [alias_sym_latex] = alias_sym_latex,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_header_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_header_token2] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_field_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACKtypst_RBRACK] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK_SLASHtypst_RBRACK] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACKlatex_RBRACK] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK_SLASHlatex_RBRACK] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__block_content_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__block_content_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_header] = {
    .visible = true,
    .named = true,
  },
  [sym_field] = {
    .visible = true,
    .named = true,
  },
  [sym_typst_block] = {
    .visible = true,
    .named = true,
  },
  [sym_latex_block] = {
    .visible = true,
    .named = true,
  },
  [sym__block_content] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_field_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__block_content_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_latex] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_body = 1,
  field_content = 2,
  field_key = 3,
  field_latex_close_tag = 4,
  field_latex_open_tag = 5,
  field_name = 6,
  field_typst_close_tag = 7,
  field_typst_open_tag = 8,
  field_value = 9,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_content] = "content",
  [field_key] = "key",
  [field_latex_close_tag] = "latex_close_tag",
  [field_latex_open_tag] = "latex_open_tag",
  [field_name] = "name",
  [field_typst_close_tag] = "typst_close_tag",
  [field_typst_open_tag] = "typst_open_tag",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 3},
  [5] = {.index = 8, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_key, 0},
    {field_value, 2},
  [2] =
    {field_name, 0},
  [3] =
    {field_body, 1},
    {field_name, 0},
  [5] =
    {field_content, 1},
    {field_typst_close_tag, 2},
    {field_typst_open_tag, 0},
  [8] =
    {field_content, 1},
    {field_latex_close_tag, 2},
    {field_latex_open_tag, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [5] = {
    [1] = alias_sym_latex,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  sym__block_content, 2,
    sym__block_content,
    alias_sym_latex,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 13,
  [15] = 11,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 17,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 21,
  [25] = 19,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(52);
      if (lookahead == ':') ADVANCE(54);
      if (lookahead == 'D') ADVANCE(28);
      if (lookahead == 'M') ADVANCE(36);
      if (lookahead == '[') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(57);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(3);
      if (lookahead == ':') ADVANCE(1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(2);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 3:
      if (lookahead == '\n') SKIP(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(2);
      if (lookahead != 0 &&
          lookahead != ':') ADVANCE(19);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(70);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(65);
      if (lookahead != 0) ADVANCE(64);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(71);
      if (lookahead == '[') ADVANCE(69);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(66);
      if (lookahead != 0) ADVANCE(64);
      END_STATE();
    case 6:
      if (lookahead == '\n') ADVANCE(72);
      if (lookahead == '[') ADVANCE(68);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(67);
      if (lookahead != 0) ADVANCE(64);
      END_STATE();
    case 7:
      if (lookahead == '/') ADVANCE(35);
      if (lookahead == 'l') ADVANCE(24);
      if (lookahead == 't') ADVANCE(48);
      END_STATE();
    case 8:
      if (lookahead == ':') ADVANCE(1);
      if (lookahead == ']') ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 9:
      if (lookahead == ':') ADVANCE(1);
      if (lookahead == ']') ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 10:
      if (lookahead == ':') ADVANCE(1);
      if (lookahead == 'a') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 11:
      if (lookahead == ':') ADVANCE(1);
      if (lookahead == 'e') ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 12:
      if (lookahead == ':') ADVANCE(1);
      if (lookahead == 'l') ADVANCE(10);
      if (lookahead == 't') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 13:
      if (lookahead == ':') ADVANCE(1);
      if (lookahead == 'p') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 14:
      if (lookahead == ':') ADVANCE(1);
      if (lookahead == 's') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 15:
      if (lookahead == ':') ADVANCE(1);
      if (lookahead == 't') ADVANCE(11);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 16:
      if (lookahead == ':') ADVANCE(1);
      if (lookahead == 't') ADVANCE(9);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 17:
      if (lookahead == ':') ADVANCE(1);
      if (lookahead == 'x') ADVANCE(8);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 18:
      if (lookahead == ':') ADVANCE(1);
      if (lookahead == 'y') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 19:
      if (lookahead == ':') ADVANCE(1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 20:
      if (lookahead == ']') ADVANCE(61);
      END_STATE();
    case 21:
      if (lookahead == ']') ADVANCE(58);
      END_STATE();
    case 22:
      if (lookahead == ']') ADVANCE(63);
      END_STATE();
    case 23:
      if (lookahead == ']') ADVANCE(60);
      END_STATE();
    case 24:
      if (lookahead == 'a') ADVANCE(42);
      END_STATE();
    case 25:
      if (lookahead == 'a') ADVANCE(44);
      END_STATE();
    case 26:
      if (lookahead == 'c') ADVANCE(32);
      END_STATE();
    case 27:
      if (lookahead == 'd') ADVANCE(29);
      END_STATE();
    case 28:
      if (lookahead == 'e') ADVANCE(26);
      END_STATE();
    case 29:
      if (lookahead == 'e') ADVANCE(33);
      END_STATE();
    case 30:
      if (lookahead == 'e') ADVANCE(46);
      END_STATE();
    case 31:
      if (lookahead == 'e') ADVANCE(47);
      END_STATE();
    case 32:
      if (lookahead == 'k') ADVANCE(53);
      END_STATE();
    case 33:
      if (lookahead == 'l') ADVANCE(53);
      END_STATE();
    case 34:
      if (lookahead == 'l') ADVANCE(25);
      END_STATE();
    case 35:
      if (lookahead == 'l') ADVANCE(25);
      if (lookahead == 't') ADVANCE(49);
      END_STATE();
    case 36:
      if (lookahead == 'o') ADVANCE(27);
      END_STATE();
    case 37:
      if (lookahead == 'p') ADVANCE(39);
      END_STATE();
    case 38:
      if (lookahead == 'p') ADVANCE(40);
      END_STATE();
    case 39:
      if (lookahead == 's') ADVANCE(41);
      END_STATE();
    case 40:
      if (lookahead == 's') ADVANCE(43);
      END_STATE();
    case 41:
      if (lookahead == 't') ADVANCE(21);
      END_STATE();
    case 42:
      if (lookahead == 't') ADVANCE(30);
      END_STATE();
    case 43:
      if (lookahead == 't') ADVANCE(23);
      END_STATE();
    case 44:
      if (lookahead == 't') ADVANCE(31);
      END_STATE();
    case 45:
      if (lookahead == 't') ADVANCE(49);
      END_STATE();
    case 46:
      if (lookahead == 'x') ADVANCE(20);
      END_STATE();
    case 47:
      if (lookahead == 'x') ADVANCE(22);
      END_STATE();
    case 48:
      if (lookahead == 'y') ADVANCE(37);
      END_STATE();
    case 49:
      if (lookahead == 'y') ADVANCE(38);
      END_STATE();
    case 50:
      if (eof) ADVANCE(52);
      if (lookahead == '\n') SKIP(50);
      if (lookahead == ':') ADVANCE(76);
      if (lookahead == '[') ADVANCE(12);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(75);
      if (lookahead != 0) ADVANCE(74);
      END_STATE();
    case 51:
      if (eof) ADVANCE(52);
      if (lookahead == '\n') SKIP(51);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(2);
      if (lookahead != 0 &&
          lookahead != ':') ADVANCE(19);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_header_token1);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym_header_token2);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(55);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(56);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_header_token2);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(56);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_field_token1);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_LBRACKtypst_RBRACK);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_LBRACKtypst_RBRACK);
      if (lookahead == ':') ADVANCE(1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_LBRACK_SLASHtypst_RBRACK);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_LBRACKlatex_RBRACK);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_LBRACKlatex_RBRACK);
      if (lookahead == ':') ADVANCE(1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_LBRACK_SLASHlatex_RBRACK);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(aux_sym__block_content_token1);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(aux_sym__block_content_token1);
      if (lookahead == '\n') ADVANCE(70);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(65);
      if (lookahead != 0) ADVANCE(64);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(aux_sym__block_content_token1);
      if (lookahead == '\n') ADVANCE(71);
      if (lookahead == '[') ADVANCE(69);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(66);
      if (lookahead != 0) ADVANCE(64);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(aux_sym__block_content_token1);
      if (lookahead == '\n') ADVANCE(72);
      if (lookahead == '[') ADVANCE(68);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(67);
      if (lookahead != 0) ADVANCE(64);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(aux_sym__block_content_token1);
      if (lookahead == '/') ADVANCE(34);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(aux_sym__block_content_token1);
      if (lookahead == '/') ADVANCE(45);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(aux_sym__block_content_token2);
      if (lookahead == '\n') ADVANCE(70);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(65);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(aux_sym__block_content_token2);
      if (lookahead == '\n') ADVANCE(71);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(66);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(aux_sym__block_content_token2);
      if (lookahead == '\n') ADVANCE(72);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(67);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\n') ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != '[') ADVANCE(76);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ':') ADVANCE(73);
      if (lookahead == '[') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(74);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ':') ADVANCE(73);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(75);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '[') ADVANCE(74);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '[') ADVANCE(76);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 50},
  [3] = {.lex_state = 50},
  [4] = {.lex_state = 50},
  [5] = {.lex_state = 50},
  [6] = {.lex_state = 50},
  [7] = {.lex_state = 51},
  [8] = {.lex_state = 51},
  [9] = {.lex_state = 4},
  [10] = {.lex_state = 4},
  [11] = {.lex_state = 5},
  [12] = {.lex_state = 51},
  [13] = {.lex_state = 6},
  [14] = {.lex_state = 5},
  [15] = {.lex_state = 6},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 51},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 55},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 55},
  [25] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_header_token1] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LBRACKtypst_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACK_SLASHtypst_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACKlatex_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACK_SLASHlatex_RBRACK] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(18),
    [sym_header] = STATE(16),
    [aux_sym_header_token1] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(5), 1,
      ts_builtin_sym_end,
    ACTIONS(7), 1,
      aux_sym_field_token1,
    ACTIONS(9), 1,
      anon_sym_LBRACKtypst_RBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACKlatex_RBRACK,
    ACTIONS(13), 1,
      sym_text,
    STATE(3), 3,
      sym_typst_block,
      sym_latex_block,
      aux_sym_field_repeat1,
  [21] = 6,
    ACTIONS(9), 1,
      anon_sym_LBRACKtypst_RBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACKlatex_RBRACK,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(17), 1,
      aux_sym_field_token1,
    ACTIONS(19), 1,
      sym_text,
    STATE(4), 3,
      sym_typst_block,
      sym_latex_block,
      aux_sym_field_repeat1,
  [42] = 6,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(23), 1,
      aux_sym_field_token1,
    ACTIONS(25), 1,
      anon_sym_LBRACKtypst_RBRACK,
    ACTIONS(28), 1,
      anon_sym_LBRACKlatex_RBRACK,
    ACTIONS(31), 1,
      sym_text,
    STATE(4), 3,
      sym_typst_block,
      sym_latex_block,
      aux_sym_field_repeat1,
  [63] = 2,
    ACTIONS(34), 1,
      ts_builtin_sym_end,
    ACTIONS(36), 4,
      aux_sym_field_token1,
      anon_sym_LBRACKtypst_RBRACK,
      anon_sym_LBRACKlatex_RBRACK,
      sym_text,
  [73] = 2,
    ACTIONS(38), 1,
      ts_builtin_sym_end,
    ACTIONS(40), 4,
      aux_sym_field_token1,
      anon_sym_LBRACKtypst_RBRACK,
      anon_sym_LBRACKlatex_RBRACK,
      sym_text,
  [83] = 3,
    ACTIONS(42), 1,
      ts_builtin_sym_end,
    ACTIONS(44), 1,
      aux_sym_field_token1,
    STATE(12), 2,
      sym_field,
      aux_sym_source_file_repeat1,
  [94] = 3,
    ACTIONS(44), 1,
      aux_sym_field_token1,
    ACTIONS(46), 1,
      ts_builtin_sym_end,
    STATE(7), 2,
      sym_field,
      aux_sym_source_file_repeat1,
  [105] = 3,
    STATE(11), 1,
      aux_sym__block_content_repeat1,
    STATE(23), 1,
      sym__block_content,
    ACTIONS(48), 2,
      aux_sym__block_content_token1,
      aux_sym__block_content_token2,
  [116] = 3,
    STATE(15), 1,
      aux_sym__block_content_repeat1,
    STATE(22), 1,
      sym__block_content,
    ACTIONS(50), 2,
      aux_sym__block_content_token1,
      aux_sym__block_content_token2,
  [127] = 3,
    ACTIONS(52), 1,
      anon_sym_LBRACK_SLASHtypst_RBRACK,
    STATE(14), 1,
      aux_sym__block_content_repeat1,
    ACTIONS(54), 2,
      aux_sym__block_content_token1,
      aux_sym__block_content_token2,
  [138] = 3,
    ACTIONS(56), 1,
      ts_builtin_sym_end,
    ACTIONS(58), 1,
      aux_sym_field_token1,
    STATE(12), 2,
      sym_field,
      aux_sym_source_file_repeat1,
  [149] = 3,
    ACTIONS(61), 1,
      anon_sym_LBRACK_SLASHlatex_RBRACK,
    STATE(13), 1,
      aux_sym__block_content_repeat1,
    ACTIONS(63), 2,
      aux_sym__block_content_token1,
      aux_sym__block_content_token2,
  [160] = 3,
    ACTIONS(61), 1,
      anon_sym_LBRACK_SLASHtypst_RBRACK,
    STATE(14), 1,
      aux_sym__block_content_repeat1,
    ACTIONS(66), 2,
      aux_sym__block_content_token1,
      aux_sym__block_content_token2,
  [171] = 3,
    ACTIONS(52), 1,
      anon_sym_LBRACK_SLASHlatex_RBRACK,
    STATE(13), 1,
      aux_sym__block_content_repeat1,
    ACTIONS(69), 2,
      aux_sym__block_content_token1,
      aux_sym__block_content_token2,
  [182] = 2,
    ACTIONS(71), 1,
      aux_sym_header_token1,
    STATE(8), 1,
      sym_header,
  [189] = 1,
    ACTIONS(73), 2,
      ts_builtin_sym_end,
      aux_sym_field_token1,
  [194] = 1,
    ACTIONS(75), 1,
      ts_builtin_sym_end,
  [198] = 1,
    ACTIONS(77), 1,
      anon_sym_COLON,
  [202] = 1,
    ACTIONS(73), 1,
      aux_sym_header_token1,
  [206] = 1,
    ACTIONS(79), 1,
      aux_sym_header_token2,
  [210] = 1,
    ACTIONS(81), 1,
      anon_sym_LBRACK_SLASHlatex_RBRACK,
  [214] = 1,
    ACTIONS(83), 1,
      anon_sym_LBRACK_SLASHtypst_RBRACK,
  [218] = 1,
    ACTIONS(85), 1,
      aux_sym_header_token2,
  [222] = 1,
    ACTIONS(87), 1,
      anon_sym_COLON,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 21,
  [SMALL_STATE(4)] = 42,
  [SMALL_STATE(5)] = 63,
  [SMALL_STATE(6)] = 73,
  [SMALL_STATE(7)] = 83,
  [SMALL_STATE(8)] = 94,
  [SMALL_STATE(9)] = 105,
  [SMALL_STATE(10)] = 116,
  [SMALL_STATE(11)] = 127,
  [SMALL_STATE(12)] = 138,
  [SMALL_STATE(13)] = 149,
  [SMALL_STATE(14)] = 160,
  [SMALL_STATE(15)] = 171,
  [SMALL_STATE(16)] = 182,
  [SMALL_STATE(17)] = 189,
  [SMALL_STATE(18)] = 194,
  [SMALL_STATE(19)] = 198,
  [SMALL_STATE(20)] = 202,
  [SMALL_STATE(21)] = 206,
  [SMALL_STATE(22)] = 210,
  [SMALL_STATE(23)] = 214,
  [SMALL_STATE(24)] = 218,
  [SMALL_STATE(25)] = 222,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 1, 0, 2),
  [7] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field, 1, 0, 2),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 2, 0, 3),
  [17] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field, 2, 0, 3),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_field_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_field_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_field_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_field_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_field_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_latex_block, 3, 0, 5),
  [36] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_latex_block, 3, 0, 5),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typst_block, 3, 0, 4),
  [40] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_typst_block, 3, 0, 4),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [50] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__block_content, 1, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__block_content_repeat1, 2, 0, 0),
  [63] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__block_content_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [66] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__block_content_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 3, 0, 1),
  [75] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_anki(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "anki",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
